# version 3.3

project:
  type: book
  output-dir: docs


published-title: "Last Modified"

book:
  title: "LDRS 663"
  author: "Colin Madland, Mark Halvorson, Scott Macklin"
  date: "last-modified"
  date-format: "MMM D, YYYY"
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - u1.qmd
    - u2.qmd
    - u3.qmd
    - u4.qmd
    - u5.qmd
    - u6.qmd    
    - assessment.qmd
    - feeds.qmd
    - obsidian.qmd
    - references.qmd
    - coaching-slides/coaching-slides.qmd

# References
bibliography: https://twuonline.github.io/course-materials/quarto/references.bib
csl: https://twuonline.github.io/course-materials/quarto/apa.csl
link-bibliography: true
link-citations: false

# Lua Filters
filters:
  - at: pre-ast
    path: yml-assets/pre.lua
  - at: post-render
    path: yml-assets/post.lua

# Add templete for block
title-block-banner: true

# ------- Format Specific Settings -------

format:
# Format - HTML
  html:
    template-partials:
      yml-assets/title-block.html
    link-external-icon: true
    link-external-newwindow: true
    sidebar:
      style: "docked"
      search: true
    css: https://twuonline.github.io/course-materials/quarto/twu_styles.css
    toc-depth: 4
    toc: true
    toc-title: On This Page
    theme: cosmo
    slide-format: revealjs
    # The line below  should only be enabled to locally test css before moving it to the main css file in course materials.
    #theme: [cosmo, yml-assets/test.scss]
    include-in-header:
    - text: |
        <script type="application/javascript" src="https://twuonline.github.io/course-materials/quarto/twu_global_header.js"></script>
        <link rel = "shortcut icon" href = "https://twuonline.github.io/course-materials/quarto/favicon.ico" />
        
# # Format - PDF
#   pdf:
#     documentclass: scrreprt

# Format - Doc
  # docx:
  #   toc: false
  #   number-sections: true
  #   highlight-style: github
  #   cite-method: biblatex
# Fig captions
# fig-cap-location: top
# lightbox:
#   desc-position: top