# Welcome {.unnumbered}

Welcome to LDRS 663: Coaching for Transformational Blended Learning

### Program Learning Outcomes {.unnumbered}
- Demonstrate effective facilitation and coaching communication skills (eg. active listening, developing rapport, providing feedback)  
- Identify a variety of facilitation/coaching methods and techniques.


### Course Learning Outcomes {.unnumbered}
On successful completion of this course, students should be able to:



- Model metacognitive strategies for self-regulated learning.   [//todo #18  ](https://github.com/ma-lead/ldrs663/issues/18)  
- Apply information and media literacies to research, produce, analyze, and present information online.   
- Design cognitive and social learning activities to meet learning outcomes.   
- Evaluate interactions in a learning environment and develop strategies for high-quality educative interactions.   
- Assess the quality of student learning processes and products in light of learning outcomes.   
- Apply intercultural competencies in coaching learners in transformational blended learning environments. [//todo #18](https://github.com/ma-lead/ldrs663/issues/18)    
- Analyze the characteristics of the coaching and facilitation roles within emerging multi-access models of blended teaching and learning.   
- Apply multi-modal communication and collaboration tools effectively to support learning in a higher education context.   






### Resources {.unnumbered}

Please note that you are not required to purchase any of the folllowing resources. They are freely available on the web or accessible through the library.

1. Biggs, J., & Tang, C. (2011). Teaching for quality learning at university: What the student does (4th ed.). New York: Society for Research into Higher Education & Open University Press. Available as eBook through TWU Library.  
2. Committee on How People Learn II: The Science and Practice of Learning, Board on Behavioral, Cognitive, and Sensory Sciences, Board on Science Education, Division of Behavioral and Social Sciences and Education, & National Academies of Sciences, Engineering, and Medicine. (2018). How People Learn II: Learners, Contexts, and Cultures. National Academies Press. [Link](https://doi.org/10.17226/24783)
3. Vaughan, N., Cleveland-Innes, M., & Garrison, D. (2013). Teaching in blended learning environments: Creating and sustaining communities of inquiry. Athabasca: AU Press. Retrieved from [Link](http://www.aupress.ca/index.php/books/120229)   
4. Bates, A. W. (2019). Teaching in a Digital Age – Second Edition. Tony Bates Associates Ltd. [Link](https://pressbooks.bccampus.ca/teachinginadigitalagev2/)
5. Campbell, G. (2009). A Personal Cyberinfrastructure. EDUCAUSE Review, 44(5), 58-59. Retrieved from https://er.educause.edu/articles/2009/9/a-personal-cyberinfrastructure  



::: {.note}



It will be assumed that you have read, understand, and agree to the information provided on the ['Academic Dishonesty Policy' page](https://www.twu.ca/about-us/policies-guidelines/university-policies/academic-misconduct-fraud){target="_blank"}. If you have any questions at all please contact your instructor.

:::

## Graduate Level Writing Standards {.unnumbered}

For students in 663, graduate level writing standards following APA 7 are expected. Please consult the [OWL Purdue website](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_style_introduction.html){target="_blank"} for guidance and seek assistance from the TWU Writing Center and writing coaches as needed. Assignments have rubrics that attribute some marks to APA formatting and cannot be graded as fully meeting expectations if there are APA errors. That said, your conceptual understanding remains of primary importance. It is your responsibility to ensure polished work to the highest standard of which you are capable. This demands meticulous attention to detail, which will become more 'natural' with practice. Please seek any necessary clarification from your instructor.
